import { fetchEnterprises, buildAccountBalance, fetchMemberDoc, updateMemberPaymentAdvice } from '../../services/dataService.js';
import { showToast } from '../../services/toastService.js';
import { formatCurrency, escapeHtml, generateId } from '../../utils/formatters.js';

export function renderAdviceSection(area) {
  area.innerHTML = `
      <h3>Payment Advice</h3>
      <p class="section-desc">Manage your monthly committed payment / savings for each account.</p>
      <div id="advice-table-container" class="table-responsive"><p style="color: var(--text-muted); font-style: italic;">Loading advice details...</p></div>
      <div style="margin-top: 1.5rem; text-align: right;">
        <button id="save-advice-btn" class="primary-button" style="padding: 0.75rem 2rem; width: ${window.innerWidth <= 768 ? '100%' : 'auto'};">Save Changes</button>
      </div>
    `;
}

export function setupAdviceListeners(user, cooperativeId) {
  const tc = document.getElementById('advice-table-container');
  const saveBtn = document.getElementById('save-advice-btn');
  if (!tc || !saveBtn) return;

  const loadAdvice = async () => {
    try {
      const [ents, balData, member] = await Promise.all([
        fetchEnterprises(cooperativeId, true),
        buildAccountBalance(cooperativeId, user),
        fetchMemberDoc(user.memberId)
      ]);

      const activeEnts = ents.filter(e => !e.is_deleted);
      const adviceMap = {};
      if (member && member.payment_advise) {
        member.payment_advise.forEach(a => adviceMap[a.enterprise_id] = a.amount);
      }

      const balanceMap = {};
      balData.accountBalance.forEach(b => balanceMap[b.id] = b.sum_of_amount);

      tc.innerHTML = `
          <table class="crud-table">
            <thead>
              <tr>
                <th style="width: 1%; white-space: nowrap;">Enterprise Account</th>
                <th style="text-align: right; width: 1%; white-space: nowrap;">Current Balance</th>
                <th style="text-align: right;">Monthly Advice</th>
              </tr>
            </thead>
            <tbody>
              ${activeEnts.map(e => {
                const balance = balanceMap[e.id] || 0;
                const advice = adviceMap[e.id] || 0;
                const isSavings = (e.account_type || '').toLowerCase() === 'savings';
                return `
                    <tr data-entid="${e.id}" data-type="${e.account_type || ''}">
                      <td style="font-weight: 600; white-space: nowrap;">${escapeHtml(e.account_name || e.id)}</td>
                      <td style="text-align: right; white-space: nowrap; color: ${balance < 0 ? 'var(--danger)' : 'inherit'};">${formatCurrency(balance)}</td>
                      <td style="text-align: right;">
                        <input type="number" step="100" class="advice-input" value="${advice}"
                          ${!isSavings ? 'disabled title="Only savings advice can be manually edited here. Loan advice is autogenerated."' : ''}
                          style="width: 100%; text-align: right; padding: 0.4rem; border: 1px solid var(--border-medium); border-radius: var(--radius-sm); background: ${!isSavings ? 'var(--bg-secondary)' : 'var(--bg-input)'}; color: var(--text-primary);">
                      </td>
                    </tr>
                  `;
              }).join('')}
            </tbody>
          </table>
        `;

      saveBtn.addEventListener('click', async () => {
        const adviceList = [];
        tc.querySelectorAll('tr[data-entid]').forEach(row => {
          const entId = row.dataset.entid;
          const input = row.querySelector('.advice-input');
          const amount = parseFloat(input.value || 0);
          if (amount !== 0) {
            adviceList.push({
              id: generateId(cooperativeId),
              amount: amount,
              created_at: new Date().toISOString()
            });
          }
        });

        try {
          saveBtn.disabled = true; saveBtn.innerText = 'Saving...'
          await updateMemberPaymentAdvice(user.memberId, adviceList, user.username);
          showToast('Payment advice updated successfully!', 'success');
        } catch (err) {
          showToast('Error: ' + err.message, 'error');
        } finally {
          saveBtn.disabled = false; saveBtn.innerText = 'Save Changes';
        }
      });
    } catch (err) {
      tc.innerHTML = `<p style="color: var(--danger);">Error loading advice: ${err.message}</p>`;
      saveBtn.style.display = 'none';
    }
  };
  loadAdvice();
}
